### ISSUE TITLE
DataFrames helpers discard options.

### ISSUE THREAD

**Issue by LMolr** [plotly/Plotly.jl#14]
The helpers regarding DataFrames integration discard passed options.
E.g:
```Julia
trace1 = Plotly.scatter(
      dataframe,
      { "name" => "TEST",
        "xs" => :idx,
        "ys" => :val })
# There shoud be a "name" => "TEST" in the result, however ..
println(trace1)
# ^- key "name" is not present.
```
I am not familiar with the language, but it looks like that the first few lines after
https://github.com/plotly/Plotly.jl/blob/master/src/plot.jl#L97
should call a `merge(get_points(...))`, but they instead just call `get_points()`.

**Comment by malmaud** [comment]
The Dataframes integration is no longer under the scope of this package - it's now delegated to https://github.com/spencerlyon2/PlotlyJS.jl.
