### ISSUE TITLE
Problem with urlencode_query_params()

### ISSUE THREAD

**Issue by DataWookie** [plotly/Plotly.jl#15]
Hi,

Just upgraded to Julia 0.4.0, installed Plotly package but found not able to produce plots due to error below:

    ERROR: MethodError: `urlencode_query_params` has no method matching urlencode_query_params(::Array{Pair{Any,Any},1})

I note that this errror also shows up here: http://pkg.julialang.org/logs/Plotly_0.4.log.

Best regards,
Andrew.

**Comment by lionpeloux** [comment]
:+1:  Same here ...

Lionel

**Comment by DataWookie** [comment]
Would be good to get this fixed. I miss running Plotly from Julia!

**Comment by DataWookie** [comment]
Looks like the actual issues was in HTTPClient. Do a Pkg.update() and it seems to be resolved.

**Comment by lionpeloux** [comment]
Good for me. Thanks.
