### ISSUE TITLE
Looking for community maintainers!

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/Plotly.jl#19]
Plotly does not have Julia expertise and we are looking for Julia community maintainers who are interested in working in consultation with the Plotly team to review and merge pull requests. If you are interested ping me on this thread or email me at ben at plot.ly

Thanks!

**Comment by malmaud** [comment]
I'll be maintaining this package, closely working with @spencerlyon2, whose [existing Plotly client](https://github.com/spencerlyon2/PlotlyJS.jl) will provide the bulk of its functionality.

**Comment by bpostlethwaite** [comment]
@chriddyp @BRONSOLO @theengineear :

@malmaud has been made maintainer of the this Repo. He has Julia experience and uses Plotly in his Graduate studies. I believe @malmaud has experience working with the web-technology end of Julia as well (can you extrapolate on that point @malmaud ?) Thanks @malmaud for stepping up! The Julia+Plotly community will be better served with someone who knows, loves and uses Julia day to day.

For a backstory on how some of the various Plotly.jl packages may come together see #18 

@malmaud : 
@chriddyp is our Product Chief at Plotly and is often involved with our language and library communities. @chriddyp has been involved with the Plotly.jl library from the beginning. 

@BRONSOLO is heavily involved in our Matlab community and has made some contributions on this Repo. 

@theengineear ( along with @chriddyp ) is a core committer on our Python Library and will be a good resource during development.

@BRONSOLO and @theengineear are the architects of our Version 2 Rest API and will be helpful during conversion to those APIs.

Exciting times ahead for Plotly+Julia!

**Comment by theengineear** [comment]
Huzzah! Thanks for stepping up @malmaud and nice to meet you! Feel free to ping me on any questions you come across!

**Comment by BRONSOLO** [comment]
Likewise! Nice to meet you @malmaud.

**Comment by jackparmer** [comment]
@malmaud @spencerlyon2 so glad to have you onboard!

@spencerlyon2 - these docs are fantastic!
http://spencerlyon.com/PlotlyJS.jl/examples/subplots/

**Comment by spencerlyon2** [comment]
@jackparmer thanks! I actually just put those up about an hour ago. That's quick feedback!

Happy to be involved, thanks for all the hard work on plotly

**Comment by malmaud** [comment]
Thanks everyone! 

Right now, I'm working on https://github.com/plotly/Plotly.jl/tree/jmm/new. Once we're done iterating on the new API it exposes, I'll merge that to master and tag a new version of Plotly.jl for the Julia community to use.

@bpostlethwaite 
>  I believe @malmaud has experience working with the web-technology end of Julia as well 

I rewrote a good chunk of https://github.com/JuliaWeb/Requests.jl, a pure-Julia HTTP client similar to Pythons' requests, to bring it close to feature parity with Python's Requests package.
