### ISSUE TITLE
Could this package here not be marked as a fork?

### ISSUE THREAD

**Issue by davidanthoff** [plotly/Plotly.jl#22]
Currently plotly/Plotly.jl appears as a fork of shirlenator/Plotly.jl on github. Given that plotly/Plotly.jl is going to be the authoritative master repo for this project, it would be nice if that fork designation was removed.

My understanding is that the owner of plotly/Plotly.jl just has to contact the github support and they will remove the fork link.

**Comment by malmaud** [comment]
Alright, I'll contact them.

**Comment by malmaud** [comment]
It's done!
