### ISSUE TITLE
show bitmap ?

### ISSUE THREAD

**Issue by jingpengwu** [plotly/Plotly.jl#23]
is there any support to show bitmap images? similar with `imshow` in matplotlib and matlab.

**Comment by spencerlyon2** [comment]
Not at the moment. I do not believe this is supported in plotly javascript.

**Comment by tbreloff** [comment]
It is supported, but I'm not sure what the Plotly commands are off the top of my head.  This works in Plots.jl with the Plotly backend:

```julia
using Plots; plotly()
heatmap(rand(10,10))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/14888154/e17e25fa-0d26-11e6-97fd-0ea8fa345bc1.png)

**Comment by tbreloff** [comment]
Actually I just realized that you want to plot a grid of RGB values, not numbers... I need to think about that one more.

**Comment by malmaud** [comment]
Plot.ly doesn't provide, so neither will its wrappers. I too would appreciate this functionality FWIW.
