### ISSUE TITLE
examples no longer works on v0.1.0 (but they do work on v0.0.3)

### ISSUE THREAD

**Issue by gustafsson** [plotly/Plotly.jl#25]
From https://plot.ly/julia/getting-started/

```
trace1 = [
  "x" => [1, 2, 3, 4],
  "y" => [10, 15, 13, 17],
  "type" => "scatter"
]
trace2 = [
  "x" => [1, 2, 3, 4],
  "y" => [16, 5, 11, 9],
  "type" => "scatter"
]

response = Plotly.plot([trace1, trace2], ["filename" => "basic-line", "fileopt" => "overwrite"])
plot_url = response["url"]
```

gives me

```
ERROR: MethodError: `convert` has no method matching convert(::Type{PlotlyJS.Plot{TT<:PlotlyJS.AbstractTrace}}, ::Array{Dict{ASCIIString,Any},1}, ::Dict{ASCIIString,ASCIIString})
This may have arisen from a call to the constructor PlotlyJS.Plot{TT<:PlotlyJS.AbstractTrace}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  PlotlyJS.Plot{T<:PlotlyJS.AbstractTrace}(::Array{T<:PlotlyJS.AbstractTrace,1}, ::Any)
  PlotlyJS.Plot(::PlotlyJS.AbstractTrace, ::Any)
  call{T}(::Type{T}, ::Any)
  ...
 in call at essentials.jl:57
 in plot at /Users/johan/.julia/v0.4/PlotlyJS/src/display.jl:75
```

(I removed warnings about deprecated Dict syntax)

On v0.0.3 however it works as documented.

**Comment by spencerlyon2** [comment]
Hi @gustafsson thank you for letting us know.

The documentation on the plot.ly website is definitely out of sync with this package. We are working on fixing this problem.

Until then, please see the [documentation](http://spencerlyon.com/PlotlyJS.jl/) and [examples](http://spencerlyon.com/PlotlyJS.jl/examples/line_scatter/) on the PlotlyJS.jl package. Hopefully soon we will move that documentation to plot.ly and there will only be one version of plotly+julia docs.

cc @jackparmer

**Comment by gustafsson** [comment]
Oh, I didn't know about PlotlyJS.jl until now. Great job @spencerlyon2 !

It would be nice if plot.ly could just put at least a simple link to the updated documentation while they sort out how to move all your documentation over there.

**Comment by spencerlyon2** [comment]
Thanks, hopefully you like using it!

@cldougl I think @gustafsson has a great recommendation. It would be nice to have a link from plot.ly/api/julia to PlotlyJS.jl while we work towards merging the two sets of docs.
