### ISSUE TITLE
No plots upon notebook refresh

### ISSUE THREAD

**Issue by dingorth** [plotly/Plotly.jl#29]
When I create fresh notebook plots works just fine. But when i reopen them, the output cell is empty.

I've tried calling `using Plotly` and `using PlotlyJS` once in the first cell and plot in other cells. None of them worked.

The errors I get from linux console: 

> [W 15:06:46.107 NotebookApp] 404 GET /static/plotly.js?v=20161201150641 (127.0.0.1) 15.30ms referer=http://localhost:8888/notebooks/program.ipynb
> Starting kernel event loops.
> [W 15:07:48.962 NotebookApp] 404 GET /static/plotly.js?v=20161201150641 (127.0.0.1) 1.90ms referer=None

And the errors I get from Chrome console:
> Failed to load resource: the server responded with a status of 404 (Not Found)
> Uncaught Error: Script error for "plotly"(…)

A large group of IT students is looking forward to getting this fixed. :)
Thanks in advance!

**Comment by spencerlyon2** [comment]
This is a tricky problem. Check out the issue over in https://github.com/spencerlyon2/PlotlyJS.jl/issues/89 and see if the suggestions there help.

If not, please report back here and let me know what happened.

**Comment by dingorth** [comment]
Seems to work at this moment. But in the past it used to stop working with no reason. Let me work with this notebook for a bit so I can confirm that this issue can be closed.

**Comment by dingorth** [comment]
It works. Thank a lot!

**Comment by dingorth** [comment]
Not working again. Here is the fault notebook:
https://github.com/dingorth/Numerical-Analysis/blob/master/pracownia2/program.ipynb
Maybe it help.
