### ISSUE TITLE
Fill between two lines

### ISSUE THREAD

**Issue by pearlzli** [plotly/Plotly.jl#34]
I'd like to request adding functionality to fill between two lines (instead of just to the x-axis). In Plots.jl, when I use the `fillrange` attribute, I get the following warning:

```
WARNING: fillrange ignored... plotly only supports filling to zero. fillrange: [10.1173,-1.86913,...]
```

**Comment by sglyon** [comment]
hey @pearlzli I this is an issue in Plots.jl

Using Plotly.jl or PlotlyJS.jl directly you can do something like this:


```

julia> using PlotlyJS

julia> x = linspace(-6, 6, 100);

julia> y = sin.(x);

julia> plot([
       scatter(x=x, y=y),
       scatter(x=x, y=y-1),
       scatter(x=x, y=y+1, fill="tonexty", fillcolor="#2602666e")],
       style=Style(color_cycle=["#260266"]))
```

which will result in 

![between_lines](https://user-images.githubusercontent.com/1001948/28045629-7de535be-659b-11e7-8c99-99d23fed530d.png)
