### ISSUE TITLE
JSON Encoder - TimeSeries

### ISSUE THREAD

**Issue by chriddyp** [plotly/Plotly.jl#4]
The Python Plotly library supports plotting several objects which can't be encoded into JSON with the default JSON encoder: `datetime`, `Pandas.Series`, `numpy.ndarray`. We should do the same for the Julia package, so that you can use objects from packages like TimeSeries directly in the `Dict`s that describe plotly graphs, e.g. 

```
dates = [Date(2012,5,29):Date(2013,5,29)]
trace1 = [
  "x" => dates, 
  "y" => rand(length(dates),1), 
  "type" => "scatter"
]
```

This would involve inspecting the object here: https://github.com/plotly/Plotly-Julia/blob/master/src/Plotly.jl#L68 and converting any non-native objects to their plotly-accepted JSON format.

Here is the Plotly-Python JSON encoder: https://github.com/plotly/python-api/blob/master/plotly/utils.py#L116-L257

And it's usage: https://github.com/plotly/python-api/blob/master/plotly/plotly/plotly.py#L1209-L1210

**Comment by milktrader** [comment]
Thanks for filing this

**Comment by snotskie** [comment]
should we maybe file this on JSON.jl? I'm thinking it'd be better handled on their end in the long run

**Comment by snotskie** [comment]
Should we file this with JSON.jl? I'm thinking it will be better handled on their end in the long run

**Comment by chriddyp** [comment]
I think that `JSON.jl` should have an optional encoder argument, sort of like the `cls` argument in python's json encoder: https://docs.python.org/2/library/json.html#json.JSONEncoder

But, since there are multiple ways to serialize e.g. a date (eg `YYYY-MM-DD` vs `YYYY/MM/DD`) and since we'll probably want to serialize objects outside of the base Julia, it should probably be up to the user to determine the string representation.. unfortunately up to us.

**Comment by snotskie** [comment]
Normally, I'd agree, but the most "julian" way to tackle this problem is to take advantage of multiple dispatch:

* have Plot.ly call JSON encode
* have JSON encode call serialize
* have serializable objects define a sensible serialize function
* and have serialize call something sensible in the generic case

**Comment by snotskie** [comment]
Looking through the sources for JSON.jl and Datetime.jl, it should actually work the way you have it in the OP, with one change: use `date` instead of `Date`. JSON.jl is defined using `print` and `string` to serialize objects, yet Date objects are being serialized to `"{}"` instead of `"YYYY-MM-DD"`In the meantime, `"x"=>map(string, dates)` works.

**Comment by milktrader** [comment]
If the end result that you'd like is this:

````julia
trace1 = [
  "x" => dates, 
  "y" => rand(length(dates),1), 
  "type" => "scatter"
]
````
Then maybe we just need a method `parse(ta::TimeArray)`

Currently, there are two methods for `JSON.parse()`

````julia
julia> methods(JSON.parse)
# 2 methods for generic function "parse":
parse(str::AbstractString) at /Users/Administrator/.julia/v0.4/JSON/src/Parser.jl:313
parse(io::IO) at /Users/Administrator/.julia/v0.4/JSON/src/JSON.jl:250
````
The way to use multiple dispatch here would be to 

````julia
import JSON.parse
function parse{T}(ta::TimeArray{T,1})  # the 1 limits the arg to one column

# containerize axes
xs = ta.timestamp
ys = ta.values
colname = ta.colnames

# possibly convert to string arrays (not sure about this)
xst = string(xs)
yst = string(ys)

# call some JSON constructor

put in some potatoes, carrots and broth 

# return the glorious result

return my result  # return keyword is optional, btw
end
````

Then create a file in the package to hold this method and `include` it in the main module. Of course, tests will be nice too :smile:

**Comment by snotskie** [comment]
The way JSON.jl is written, it's supposed to already handle dates properly (or anything that can be `print`ed really), so I filed an issue with them. What you have could work in the meantime as a workaround, though I guess a more direct approach would be to investigate JSON.jl directly and file a pull request with the fix. I can work on that starting next week

**Comment by milktrader** [comment]
What issue did you file?

I don't see a issue with JSON handling `Date` or `DateTime`, but I'm not sure if that's what Plotly uses to build charts.

I don't think JSON will add a method dispatched on TimeArrays. That's sorta the point of multiple dispatch, you extend methods yourself. This keeps the mothership from being needlessly cluttered.

**Comment by milktrader** [comment]
Okay, here is the issue https://github.com/JuliaLang/JSON.jl/issues/90

**Comment by snotskie** [comment]
JSON.jl takes advantage of the multiple dispatch of functions like `print` and `string`, which almost every type defines for themselves. This way, it doesn't need to make a specific parse for `Date`s/etc. However, somewhere a call to print/etc. is being missed or something. My issue is [here](https://github.com/JuliaLang/JSON.jl/issues/90) about this.
