### ISSUE TITLE
plotly() as backend to Plots.jl not working

### ISSUE THREAD

**Issue by AtheistApe** [plotly/Plotly.jl#41]
I'm trying to get plotly to work as a backend to Plots.jl but have no luck with either Julia 0.7, Julia 1.01 or Julia 1.10.

With Julia 0.7, I get no error messages but no plots display (blank canvas).

With both Julia 1.01 and 1.10, I get the following error message:
"only png or svg allowed. got: :html"

I'm using this in a Jupyter notebook (Anaconda install) in google chrome browser.

**Comment by sglyon** [comment]
Thanks for your interest!

While it is a bit confusing, this package is totally unrelated to (and unused by) Ploty.jl.

In order to get the proper help you'll want to open an issue over in that repo.

Best of luck!
