### ISSUE TITLE
Pkg.installed() was deleted; don't use it (ERROR: UndefVarError: installed not defined)

### ISSUE THREAD

**Issue by luchr** [plotly/Plotly.jl#44]
Precompiling Plotly.jl on current trunk gives:

```
ERROR: UndefVarError: installed not defined
```

Why? Because of the line in `v2.jl`
```
const _VERSION = string(Pkg.installed()["Plotly"])
```
There is no `Pkg.installed` anymore.

The next highly experimental feature seems to be `Pkg.dependencies()`, hence something like this:
```
const _VERSION = first(filter( kv_pair -> kv_pair.second.name == "Plotly", Pkg.dependencies())).second.version
```
I definitely hope, some Julia-Pkg-master finds a better solution for something simple like: Find the version of a installed package by name.

**Comment by sglyon** [comment]
I think we can probably delete that line and remove the reference to it later on in the ilfe

**Comment by luchr** [comment]
This is a good idea.
