### ISSUE TITLE
Got errors when running the example in tutorial

### ISSUE THREAD

**Issue by woshidama323** [plotly/Plotly.jl#46]
ENV
1. julia 1.2
(v1.2) pkg> status
    Status `~/.julia/environments/v1.2/Project.toml`
  [31a5f54b] Debugger v0.6.2
  [28b8d3ca] GR v0.44.0
  [cd3eb016] HTTP v0.8.8 #master (/root/HTTP.jl)
  [7073ff75] IJulia v1.20.2
  [41391dba] InfluxDB v0.1.0 #master (https://github.com/staticfloat/InfluxDB.jl.git)
  [0f8b85d8] JSON3 v0.1.13
  [a93385a2] JuliaDB v0.13.0
  [ee78f7c6] Makie v0.9.5
  [a15396b6] OnlineStats v1.0.2
  [58dd65bb] Plotly v0.2.0
  [91a5bcdd] Plots v0.27.1
  [92933f4c] ProgressMeter v1.2.0
  [438e738f] PyCall v1.91.2
  [d330b81b] PyPlot v2.8.2
  [104b5d7c] WebSockets v1.5.2+ #master (/root/WebSockets.jl/)

ISSUE:
```
Plotly.set_credentials_file({“username”=>“DemoAccount”,“api_key”=>“lr1c37zw81”})
ERROR: syntax: { } vector syntax is discontinued
```

Here , I have replaced the username and api_key with my own one

**Comment by sglyon** [comment]
Hi @woshidama323 which tutorial are you referring to? Could you please provide a link?

**Comment by hhaensel** [comment]
I had the same error this morning. Apparently, the syntax has changed and the plotly Julia docs are not updated yet.

try something like
```
plot(scatter(x=0:40, y=(0:40).^2, mode="lines"))

x = 0:π/20:4π |> collect
y = 0:π/20:4π |> collect
z = 5 .*sin.(x) * cos.(y)' |> collect
plot(surface(x = x, y = y, z = z))
```

More examples can be perhaps translated form the plotly [python docs](https://plot.ly/python/line-charts/#label-lines-with-annotations)

**Comment by hhaensel** [comment]
Furthermore, you may want to consider the use of PlotlyJS. Parts of their [documentation ](http://spencerlyon.com/PlotlyJS.jl/examples/line_scatter/) helped me as well

**Comment by sglyon** [comment]
Hi @woshidama323  and @hhaensel 

Thanks for bringing this up and looking at it.

This package indeded uses PlotlyJS.jl under-the-hood for all plotting. 

So, any of the docs from over there will apply to Plotly.jl

**Comment by hhaensel** [comment]
Would be great to include this information in the `readme.md` 😉

**Comment by sglyon** [comment]
Thanks -- it is there!
