### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by DilumAluthge** [plotly/Plotly.jl#47]
Can you tag a new release of Plotly?

**Comment by sglyon** [comment]
I'd be happy to tag a new release on github, but don't have time to generate a Project.toml file. Would anyone be willing to do that?

**Comment by montyvesselinov** [comment]
done:

https://github.com/plotly/Plotly.jl/pull/48

Thank you very much!

**Comment by montyvesselinov** [comment]
can you know register at

https://pkg.julialang.org/registrator/

**Comment by sglyon** [comment]
finally got it!
