### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by milktrader** [plotly/Plotly.jl#5]
I got an email from @astrieanna (owner of the original repo) that it's fine for us to go ahead and register this package with Julia's METADATA.

First thing will be to rename it to __Plotly.jl__

Next, follow the package registration workflow. Here is some [documentation](http://julia.readthedocs.org/en/latest/manual/packages/#package-development) on how to do this. It's fairly straightforward.

I'll keep tabs on it and merge it once it gets up, and manage any quirks if they come up.

**Comment by snotskie** [comment]
Did you guys ever get the chance to look at my [pull request](https://github.com/plotly/Plotly-Julia/pull/3)?

**Comment by bpostlethwaite** [comment]
Oh wow @snotskie sorry. I think this is one of those things that must have been lost in the crazy cloud (we were fundraising last summer and things were super busy). I'll review this later this week and weekend. Anything change in as far as Julia versions since then?

**Comment by bpostlethwaite** [comment]
@milktrader Great thanks! I'll take a week or so to acquaint myself with this package again, take it for a test drive, review some existing PRs etc. I'll ping you if I encounter any problems once I start on the reg-work.

**Comment by milktrader** [comment]
Okay, great @bpostlethwaite 

There is a manual way of doing this, which requires some familiarity with git PRs and so forth, but the docs demonstrate using some helper methods that takes care of this for you (i.e., 'Pkg.tag', 'Pkg.register', etc).

**Comment by snotskie** [comment]
@bpostlethwaite I'm currently using my branch with julia 0.3.5 with no troubles

**Comment by bpostlethwaite** [comment]
Okay, awaiting JuliaLang/METADATA.jl/pull/2050
