### ISSUE TITLE
pie chart is showing nothing

### ISSUE THREAD

**Issue by islent** [plotly/Plotly.jl#51]
Basic plotting is working (interactive):
```julia
Plotly.plot(rand(10), rand(10))
```

And plotly backend works in Plots (noninteractive, opens in browser):
```
using Plots
plotly()
x = ["Nerds", "Hackers", "Scientists"]
y = [0.4, 0.35, 0.25]
pie(x, y, title = "The Julia Community", l = 0.5)
```

However, pie charts in Plotly gives out a blank output:
```julia
using Plotly
x = ["Nerds", "Hackers", "Scientists"]
y = [0.4, 0.35, 0.25]
data = Dict(x .=> y)
Plotly.plot(pie(data, title = "The Julia Community", l = 0.5))
```
![image](https://user-images.githubusercontent.com/31057826/80449464-ce04d180-8951-11ea-95f3-05e047d744c0.png)
This is totally weird!

Some info that might be useful:
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4940MX CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_DEPOT_PATH = F:\Julia-1.4.0\.julia;F:\Julia-1.4.0\local\share\julia;F:\Julia-1.4.0\share\julia;
  JULIA_NUM_THREADS = 8
  JULIA_REVISE_INCLUDE = 1
  JULIA_REVISE_POLL = 1

(@v1.4) pkg> st Plotly
Status `F:\Julia-1.4.0\.julia\environments\v1.4\Project.toml`
  [58dd65bb] Plotly v0.3.0
```

**Comment by sglyon** [comment]
Hi @islent it looks like you are using Plots.jl syntax with the Plotly.jl (behind the scenes using PlotlyJS.jl) package

To get this to work properly you should follow the arguments used by plotly.js (some docs here: https://plotly.com/javascript/pie-charts/)

This example works for me:

```julia
using Plotly
x = ["Nerds", "Hackers", "Scientists"]
y = [0.4, 0.35, 0.25]
plot(pie(values=y, labels=x), Layout(title="The Julia Community"))
```

**Comment by sglyon** [comment]
pltoly

**Comment by islent** [comment]
@sglyon It worked!
Thanks for reply and apology for my late reply and stupidity :D
I was confused by Plotly's keyword syntax. Now I get it 😄

**Comment by sglyon** [comment]
No problem glad we got it to work!
