### ISSUE TITLE
quiver throws error with null arrow

### ISSUE THREAD

**Issue by rmsrosa** [plotly/Plotly.jl#54]
Hi, I am trying to plot a vector field, but plotly is throwing an error when the vector is zero. No problem with the gr backend, only with plotly. I don't know whether it is a but or there is an argument to avoid that. Here is what happens:
```julia
julia> gr()
Plots.GRBackend()

julia> quiver([0.0], [0.0], quiver=([0.0],[0.0]))

julia> plotly()
Plots.PlotlyBackend()

julia> quiver([0.0], [0.0], quiver=([1.0],[1.0]))

julia> quiver([0.0], [0.0], quiver=([0.0],[0.0]))
Error showing value of type Plots.Plot{Plots.PlotlyBackend}:
ERROR: UndefRefError: access to undefined reference
```

I can show the full stack error if it helps. I am using Julia 1.5.3 and Plots 0.3.0

**Comment by sglyon** [comment]
Hi @rmsrosa 

This looks to be an issue in the Plots.jl package.

The `plotly` backend over there is actually self contained and not related to Plotly.jl here. sorry about the confusion!
