### ISSUE TITLE
Documentation may be out of date

### ISSUE THREAD

**Issue by alexlenail** [plotly/Plotly.jl#56]
I tried to run two examples: 
- https://plotly.com/julia/time-series/
- https://plotly.com/julia/3d-surface-plots/

Both of them errored with

```
MethodError: no method matching Plot(::Vector{Vector{Pair{String, Any}}}, ::Vector{Pair{String, String}})
Closest candidates are:
...
```

And I just installed Plotly with `] add Plotly`.

If the methods have changed, I'd love to see the docs updated as well.

**Comment by sglyon** [comment]
Thank you for letting us know! We are actively working on this and should have some updated docs soon.

For now, please see the documentation for PlotlyJS.jl -- the plot creation commands all apply to Plotly.jl also

http://juliaplots.org/PlotlyJS.jl/stable/
