### ISSUE TITLE
Is there a way to add a horizontal line on a categorical box plot?

### ISSUE THREAD

**Issue by michaelschwob** [plotly/Plotly.jl#66]
So, I am using PlotlyJS to build grouped box plots, and I want a horizontal line that runs directly through all boxplots for each grouping. I tried to find a way to accomplish this, perhaps by adding a long tick at the y-intercept. However, I was unable to accomplish this. Thank you.

**Comment by empet** [comment]
You should call the function `add_hline!()`:
```
using PlotlyJS, Distributions
y1= rand(Normal(), 50) .-0.5
y2 =rand(Normal(), 50) .+0.3
pl= Plot(box(y=y1),Layout(width=700, height=450))
add_trace!(pl,  box(y=y2))
add_hline!(pl, 1.2;) #draws the horizontal line y=1.2
display(pl)
```
Please post your questions  on [https://discourse.julialang.org/](https://discourse.julialang.org/),  because  it is  unlikely to be seen here, as this package is watched by only a few of those who might answer.

**Comment by michaelschwob** [comment]
Will do - thank you!
