### ISSUE TITLE
Link to to documentation on README.md appears broken

### ISSUE THREAD

**Issue by Eetion** [plotly/Plotly.jl#67]
The link given for documentation is `http://spencerlyon.com/PlotlyJS.jl/`, but for me this gives a 404 / page not found.  Has the documentation moved?

**Comment by empet** [comment]
The documentation for the last version is here: [https://github.com/plotly/plotlyjs.jl-docs/tree/master/julia](https://github.com/plotly/plotlyjs.jl-docs/tree/master/julia) or here:  [https://plotly.com/julia/](https://plotly.com/julia/), while PlotlyBase reference, here [https://plotly.com/julia/reference/](https://plotly.com/julia/reference/).

**Comment by Eetion** [comment]
Great, that helps.  Should someone open up a pull request to update the readme?

**Comment by empet** [comment]
No, you shouldn't open up a PR. plotly.jl is used only for uploading a plot to Plotly cloud. You landed in a wrong place, here. As I mentioned above, the github repo for Julia version of plotly.py/plotly.js is PlotlyBase.jl/PlotlyJS.jl. The right README, and link to initial docs are here [https://github.com/JuliaPlots/PlotlyJS.jl](https://github.com/JuliaPlots/PlotlyJS.jl). Unlike the examples at the links I posted yesterday, for the last version, these docs present the structs involved in the definition of a Plotly figure, and more. Hence, depending on whether an user is a beginer or not, he should start from the initial docs or the docs for the last version.

**Comment by Eetion** [comment]
Thanks, and I promise I'll stop harping on this, but the readme at https://github.com/JuliaPlots/PlotlyJS.jl only has four links:

- https://plot.ly/javascript, which points to Plotly Java Script (using their search bar for "Julia" doesn't return any results).
- https://github.com/plotly/Plotly.jl (which points back to this repo)
- https://github.com/sglyon/PlotlyJS.jl/issues/83 (issue report for installation)
- https://jupyterlab.readthedocs.io/en/stable/user/extensions.html (for the jupyter lab extension)

So even between the two repos, it doesn't seem clear how someone would find directions to get to the right place. Of course, other people may have better googling skills than I do.

**Comment by empet** [comment]
There is button: docs stable.

**Comment by Eetion** [comment]
Ah!  Of course.
