### ISSUE TITLE
Very Long Precompile

### ISSUE THREAD

**Issue by sonofwatt84** [plotly/Plotly.jl#69]
I'm having an issue where Plotly.jl either takes an extremely long time to precompile (more than 12 hours), or it's hanging.  All the other packages I'm using install fine.  Any advice on resolving this issue, or getting more verbose output?

**Comment by sonofwatt84** [comment]
I'm using both.  From my understanding, Plotly.jl depends on PlotlyJS.jl.  Plotly.jl is a dependency for the third library, which I'm working with.

I haven't been able to replicate this on other systems.  Seems to work fine on a fresh install of Julia on Ubuntu.  The system with the issue is running Windows with a user installation of Julia.  The issue seems to be the same for both Julia 1.9.3 and 1.9.4.

**Comment by empet** [comment]
Please ask questions about how to troubleshoot the various Julia versions of Plotly, such as PlotlyJS.jl, PlotlyLight.jl, PlutoPlotly.jl, at [https://discourse.julialang.org](https://discourse.julialang.org).  Do you need Plotly.jl to use plotly backend with Plots.jl?

**Comment by sonofwatt84** [comment]
Okay, thanks.  I need this library because it's a dependency.  Don't have a lot choice in the matter.
I deleted my .julia directory, and tried completely rebuilding my environment, but nothing improves.  

If you say the julia discourse server is the appropriate place for troubleshooting this library, so be it.

**Comment by empet** [comment]
Are you using Plotly.jl or PlotlyJS.jl? The former is obsolete. The latter is installed as any julia package:
```
using Pkg
Pkg.install("PlotlyJS")
```
Then it is precompiled in a few seconds.
